#on: 
#  workflow_dispatch:
#    inputs:
#      environment:
#        description: "Chose environment"
#        required: true
#        default: "staging"
#        type: choice
#        options:
#          - staging
#          - production
           
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Deploy application
#        run: echo "Deploying the application to ${{inputs.environment}}"
on:
  repository_dispatch:
    types: [incident_report]
jobs:
  handle-incident:
    runs-on: ubuntu-latest
    steps:
      - name: Print incident details
        run: echo "Incident reported"
