on:
  push:
    branches:
      - main
      - "/release/**"
    paths:
      "src/**"
  pull_request:
    - main
    - "release/**"

job:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v7.0.0
      
    - name: run tests
      run: npm test
    

